'use client';

import { DataGrid, DataGridActions, GridProps } from '@/components/DataGrids';
import { GridColDef } from '@mui/x-data-grid';
import { StatusChips } from '@/components/Chips';
import { DeliveryPlan } from '@/api';
import { getIndexedRows } from '@/utils';

const PlanningGrid = ({ rows, isLoading, ...otherProps }: GridProps<DeliveryPlan>) => {
   const columns: GridColDef[] = [
      {
         field: 'id',
         headerName: 'No.',
         width: 50,
         sortable: false,
      },
      {
         field: 'DeliveryPlanNO',
         headerName: 'Delivery Plan NO.',
         width: 150,
      },
      {
         field: 'SourceVendorLocationName',
         headerName: 'Source Location',
         width: 150,
      },
      {
         field: 'VendorLocationName',
         headerName: 'Location',
         width: 150,
      },
      {
         field: 'DriverName',
         headerName: 'Driver Name',
         width: 150,
      },
      {
         field: 'DeliveryPlanTypeName',
         headerName: 'Delivery Plan Type',
         width: 150,
      },
      {
         field: 'GeneratedBy',
         headerName: 'Generated By',
         width: 150,
      },
      {
         field: 'DeliveryPlanStatusName',
         headerName: 'Status',
         width: 150,
         renderCell: ({ row: { DeliveryPlanStatusName, DeliveryPlanStatusID } }) => {
            return <StatusChips name={DeliveryPlanStatusName} statusID={DeliveryPlanStatusID} />;
         },
      },
      {
         field: 'Actions',
         headerName: 'Actions',
         type: 'actions',
         getActions: () => [<DataGridActions key="actions" />],
      },
   ];

   return (
      <DataGrid columns={columns} rows={getIndexedRows(rows)} loading={isLoading} {...otherProps} />
   );
};

export default PlanningGrid;
