'use client';

import { DeliveryPlan, APPCRUD } from '@/api';
import { StatusChips } from '@/components/Chips';
import { TablessContainer } from '@/components/Containers';

type Params = {
    VendorLocationID: number;
    DeliveryPlanStatusID: number;
    DeliveryPlanTypeID: number;
};

const Planning = () => {
    const UI = new APPCRUD<DeliveryPlan, void, void, Params>({
        grid: {
            pagination: false,
            fetchUrl: 'getDeliveryPlanHistory',
            params: {
                VendorLocationID: 0,
                DeliveryPlanStatusID: 99,
                DeliveryPlanTypeID: 0,
            },
            columns: [
                { field: 'DeliveryPlanNO', headerName: 'Delivery Plan NO.', width: 150 },
                { field: 'SourceVendorLocationName', headerName: 'Source Location', width: 150 },
                { field: 'VendorLocationName', headerName: 'Location', width: 150 },
                { field: 'DriverName', headerName: 'Driver Name', width: 150 },
                { field: 'DeliveryPlanTypeName', headerName: 'Delivery Plan Type', width: 150 },

                { field: 'GeneratedBy', headerName: 'Generated By', width: 150 },
                {
                    field: 'DeliveryPlanStatusName',
                    headerName: 'Status',
                    width: 150,
                    renderCell: ({ row: { DeliveryPlanStatusName, DeliveryPlanStatusID } }) => {
                        return <StatusChips name={DeliveryPlanStatusName} statusID={DeliveryPlanStatusID} />;
                    },
                },
            ],
        },
    });

    return (
        <TablessContainer headerName="Planning" subTitle="Manage your delivery plans, view, add and delete.">
            {UI.render()}
        </TablessContainer>
    );
};

export default Planning;
